### ISSUE TITLE
Player cannot unpause the game

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#127]
Tested in a Build.

When the player pauses the game, and then tries to resume it, he will notice the Pause menu will never actually close, causing the player to become stuck in the menu.

If he tries to go back to the Character Select screen, the screen will remain black and prevent the player from seeing anything,

**Comment by symbol24** [comment]
Fixed, but this has probably nothing todo with #101, try to repro it with this fix, if you still can get it, ill find a fix, if you cant, well... shhhh

**Comment by BenGoulet** [comment]
Somehow am the only one to still have this issue, out of three people. It is 100%, on my end.
All I do is turn on two Player Datas in the Hierarchy, play the game and try to press Start, and then Start again to close the Pause Menu.

**Comment by symbol24** [comment]
I cant get it, i dont know whats going on, I know jeff got it, but you guys need to find out when you are getting it on jeffs.

**Comment by BenGoulet** [comment]
Occurs only when you press the A Button when highlighting the Resume option.

**Comment by jeffcerto** [comment]
checked and fixed
