### ISSUE TITLE
Missing vibrations for the player to set

### ISSUE THREAD

**Issue by BenGoulet** [symbol24/ProjectJuice#139]
The following actions do not trigger vibrations and the player does not have control over them in the Inspector:

No vibration for Dash/Air Dash.
No vibration for melee (should be a different vibration when hitting, and when being hit).
No vibration for battle axe.
Missing vibration when pushing crates and barrels.

**Comment by monstervictor** [comment]
Added Dash/Air dash vibrations.
Added melee vibrations

Missing battle axe
Added on 18-11-2015

Missing pushing crates and barrels

**Comment by monstervictor** [comment]
Missing only: 
Vibration felt from the explosion of a barrel --> Added new bug for it

**Comment by BenGoulet** [comment]
Current status:
Melee works.
Pushing crates/barrels works.
Dash and Air Dash do NOT work.
Battle Axe does NOT work.

**Comment by BenGoulet** [comment]
Note: Even with the battle axe dealing damage again, its vibrations still don't work.

**Comment by monstervictor** [comment]
Dash and Air dash have been fixed
Battle Axe vibrations are fixed as well

**Comment by BenGoulet** [comment]
Dash and Air Dash are good now, but the Grounded Battle Axe still does not make other players vibrate.
Dropping to Prio 3, since this can easily be dropped.

**Comment by jeffcerto** [comment]
checked and fixed
