### ISSUE TITLE
If the player controller is vibrating and the player pauses and goes to main menu, the vibration still occures

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#152]

**Comment by symbol24** [comment]
same issue as #141. victor does not stop the vibration at the moment.

**Comment by monstervictor** [comment]
This was fixed, Vibrations stop at pause and continue at unpause.
Vibrations are completely stop at end of round

**Comment by BenGoulet** [comment]
Still occurs for the fully charged Juice Shield.

**Comment by monstervictor** [comment]
Shield vibrations at pause has been fixed, I will be pushing soon

**Comment by BenGoulet** [comment]
It is fixed in the Pause menu (although you still hear its sound), but if you have the fully charged shield and go back to the main menu, you will still feel the vibrations and the sound.

**Comment by BenGoulet** [comment]
Still occurs:
Have the Shield, have someone shoot it until it is fully charged, go back to the main menu: Vibrationes.

**Comment by BenGoulet** [comment]
Seems fixed.
